FROM python:3.10.1


WORKDIR /app

COPY ./requirements.txt .

RUN pip install --no-cache-dir --upgrade -r /app/requirements.txt

COPY ./main.py .
COPY ./model.py .

EXPOSE 8501

CMD ["streamlit", "run", "--server.port", "8501", "main.py"]