services:
  backend:
    build: backend/
    image: backend
    ports:
      - "8000:8000"
    depends_on:
      - mongo
    links:
      - mongo:db    


  frontend:
    build: frontend/
    image: frontend
    ports:
      - "8501:8501"
    depends_on:
      - backend


  mongo:
    image: mongo:latest
    restart: always
    container_name: db-container
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin
    volumes:
      - mongo_data:/data/db
    ports:
      - 27017:27017
    
  # tests:
  #   build: backend/
  #   image: backend-tests
  #   depends_on:
  #     - mongo
  #   links:
  #     - mongo:db
  #   command: pytest testing.py


volumes:
  mongo_data:



      

